spring:
  # 设置接口超时时间
  mvc:
    async:
      request-timeout: 20000
  thymeleaf:
    cache: false
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cache:
    type: redis
  # REDIS数据库配置
  redis:
    # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
    host: ${REDIS_HOST:127.0.0.1}
    # [必须修改] 端口号
    port: ${REDIS_PORT:6379}
    # [可选] 数据库 DB
    database: ${REDIS_DB:6}
    # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
    password: ${REDIS_PWD:}
    # [可选] 超时时间
    timeout: 10000
  # [必选] jdbc数据库配置
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          # url: jdbc:mysql://mysql:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowMultiQueries=true
          url: jdbc:mysql://mysql:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&serverTimezone=PRC&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
          username: root
          password: root123
          hikari:
            connection-timeout: 20000 # 是客户端等待连接池连接的最大毫秒数
            initialSize: 50 # 连接池初始化连接数
            maximum-pool-size: 200 # 连接池最大连接数
            minimum-idle: 10 # 连接池最小空闲连接数
            idle-timeout: 300000 # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
            max-lifetime: 1200000 # 是池中连接关闭后的最长生命周期（以毫秒为单位)

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
  port:
    18080
    # [可选] HTTPS配置， 默认不开启
  ssl:
    # [可选] 是否开启HTTPS访问
    enabled: true
    # [可选] 证书文件路径，放置在resource/目录下即可，修改xxx为文件名
    key-store: classpath:wvp.jks
    # [可选] 证书密码
    key-store-password: Sa123456
    # [可选] 证书类型， 默认为jks，根据实际修改
    key-store-type: JKS
    # 私钥文件
    # certificate-private-key: private.key

# 作为28181服务器的配置
sip:
  # [必须修改] 本机的IP，对应你的网卡，监听什么ip就是使用什么网卡，
  # 如果要监听多张网卡，可以使用逗号分隔多个IP， 例如： 192.168.1.4,10.0.0.4
  # 如果不明白，就使用0.0.0.0，大部分情况都是可以的
  # 请不要使用127.0.0.1，任何包括localhost在内的域名都是不可以的。
  ip: 0.0.0.0
  # [可选] 28181服务监听的端口
  port: ${WVP_PORT:5060}
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  # [可选]
  domain: ${WVP_DOMAIN:4401020049}
  # [可选]
  id: ${WVP_ID:44010200492000000001}
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: ${WVP_PWD:admin123}

#zlm 默认服务器配置
media:
  # [必须修改] zlm服务器唯一id，用于触发hook时区别是哪台服务器,general.mediaServerId
  id: 0fAvwxFm58UeUkn6
  # [必须修改] zlm服务器的内网IP
  ip: ${WVP_HOST}
  # [可选] 有公网IP就配置公网IP, 不可用域名
  wan_ip:
  # [必须修改] zlm服务器的http.port
  http-port: 8080
  # [可选] zlm服务器的http.sslport, 置空使用zlm配置文件配置
  http-ssl-port: 8443
  # [可选] zlm服务器访问WVP所使用的IP, 默认使用127.0.0.1，zlm和wvp没有部署在同一台服务器时必须配置
  hook-ip: ${WVP_HOST}
  # [可选] zlm服务器的hook.admin_params=secret
  secret: 3V8BiOysJDN2749J7ecLskomU3ATJvgr
  # [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
  # auto-config: true
  # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
  rtp:
    # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
    enable: true
    # [可选] 在此范围内选择端口用于媒体流传输,
    port-range: 30000,30500 # 端口范围
    # [可选] 国标级联在此范围内选择端口发送媒体流,
    send-port-range: 30000,30500 # 端口范围
  # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
  record-assist-port: 18081
  sdp-ip: ${WVP_HOST}
  stream-ip: ${WVP_HOST}

# [根据业务需求配置]
user-settings:
  # 点播/录像回放 等待超时时间,单位：毫秒
  play-timeout: 180000
  # [可选] 自动点播， 使用固定流地址进行播放时，如果未点播则自动进行点播, 需要rtp.enable=true
  auto-apply-play: true
  # 推流直播是否录制
  record-push-live: true
  # 国标是否录制
  record-sip: true
  # 国标点播 按需拉流, true：有人观看拉流，无人观看释放， false：拉起后不自动释放
  stream-on-demand: true
  # [可选 ] 录像保存时长（单位： 天）每天晚12点自动对过期文件执行清理
  recordDay: 7
  # [可选 ] 录像下载合成临时文件保存时长， 不配置默认取值recordDay（单位： 天）每天晚12点自动对过期文件执行清理
  # recordTempDay: 7
  # [必选 ] ffmpeg路径
  ffmpeg: /usr/bin/ffmpeg
  # [必选 ] ffprobe路径， 一般安装ffmpeg就会自带， 一般跟ffmpeg在同一目录,用于查询文件的信息
  ffprobe: /usr/bin/ffprobe
  # [可选 ] 限制 ffmpeg 合并文件使用的线程数，间接限制cpu使用率， 默认2 限制到50%
  threads: 2
